### PR TITLE
Documentation update, API Reference

### PR DESCRIPTION
**Pull request by bfoder**
Hi,

I've made some changes in documentation:

- Config updated, autodoc enabled.
- API Reference documentation updated and moved to code as docstrings.
- Documentation requirements updated.
- .gitignore updated, for PyCharm

### CODE REVIEW

**Comment by rhdxmr** [comment]
@bfoder @cybergrind  I will look into this PR soon 😄

**Comment by cybergrind** [comment]
Probably the one thing I would actually change is to move type definitions from comments into type annotations. Anyway, it isn't the case here.
@rhdxmr Most of PR just move things from `api.rst` and if there are no other major changes we need just check if RTD works after these changes

**Comment by rhdxmr** [comment]
Hello @bfoder
First, I appreciate your nice work :+1: :100: 

I merged your PR into rtd-test branch and read the document.
But there are little flaws at .set, .get_children, .begin_transaction of ZKClient.
https://aiozk.readthedocs.io/en/rtd-test/api.html

Could you check this out?

**Comment by rhdxmr** [comment]
@cybergrind Type-annotations? that's a good idea.
It would be good to add some type-annotations via other PRs in the near future :) 
That can help improve the stability of aiozk.

**Comment by bfoder** [comment]
@rhdxmr yes, I will correct it soon.  

I also forgot to describe parameters in methods of Transaction class, will take care of that too.

**Comment by rhdxmr** [comment]
It looks good to me. I am merging this PR gladly. Thanks, @bfoder :+1: 

I just wonder why only Transaction.commit is described as `coroutine` while other coroutines are described as `async`. Do you know how to fix this?

**Review by rhdxmr — APPROVED** [review]

**Review by rhdxmr — APPROVED** [review]

**Comment by rhdxmr** [comment]
@bfoder, I just merged your PR.
But both of 'merging by merge commit' and 'merging by rebase' were not available.
So I chose the other merging method left, and it worked but your 4 commits are united into one commit. I feel sorry about that.
Next time, I'll ask you to rebase the PR based on current master branch.

**Pull request merged**
