### PR TITLE
event loop: Create Futures in a pedantic way

### PR DESCRIPTION
**Pull request by rhdxmr**
Specify event loops explicitly everytime futures are created

### CODE REVIEW

**Comment by rhdxmr** [comment]
@cybergrind 
I send you new PR about specifying event loops for Futures. :relaxed:

**Comment by rhdxmr** [comment]
I'll rebase my branch onto micro-fan:master and re-send this soon

**Comment by cybergrind** [comment]
@rhdxmr ok, great. Also, I've sent you invite, after you accept it you may create branches inside this repo, it will make rebases easier to me too

**Comment by rhdxmr** [comment]
@cybergrind Great! I accepted the invitation. Thank you.

**Comment by rhdxmr** [comment]
@cybergrind 
I'm gonna rebase onto the mater branch after PR#58 is merged successfully.
Because that the error incurred at Travis CI is solved by PR#58

**Comment by cybergrind** [comment]
:+1:

**Pull request merged**
