### PR TITLE
barrier: Add test for no barrier, no blocking case

### PR DESCRIPTION
**Pull request by rhdxmr**
I'm reviewing barrier recipes now.

### CODE REVIEW

**Comment by rhdxmr** [comment]
How are you @cybergrind 😀
Are you OK in a COVID-19 situation?
I live in Seoul, South Korea. It's OK here.

**Comment by cybergrind** [comment]
@rhdxmr all is good, I've reviewed you PR's and they looks ok, but couldn't rebase it correctly from web interface, will merge soon

**Comment by rhdxmr** [comment]
@cybergrind
I'm glad to hear that. Stay safe home.

**Comment by cybergrind** [comment]
merged in v0.24.0

**Pull request closed without merging**
