### PR TITLE
Fix lock timeout accuracy

### PR DESCRIPTION
**Pull request by rhdxmr**
subtract the used time before it starts waiting for siblings to be deleted.

### CODE REVIEW

**Comment by rhdxmr** [comment]
Hello @cybergrind
I created a new PR. Can you review this?

**Comment by cybergrind** [comment]
Released as 0.22.0

**Comment by rhdxmr** [comment]
what a quick merge

**Comment by cybergrind** [comment]
@rhdxmr 1 line quick and obvious fix =) not too much to review

**Pull request merged**
