### PR TITLE
Fix deadlock incurred by lock acquisition failure

### PR DESCRIPTION
**Pull request by rhdxmr**
A znode of Zookeeper related to a lock becomes untracked if session suspension occurs while acquiring a lock.

By this patch, TimeoutError raised at .analyze_siblings() is handled properly and make the lock acquisition procedure keep going until timeout is reached.

### CODE REVIEW

**Comment by rhdxmr** [comment]
Long time no see, @cybergrind 
Can you review my PR?
And please check why docker-compose build failed.
It seems that downloading zookeeper by curl has some problem.

**Comment by rhdxmr** [comment]
@cybergrind 
I also sent PR#49 to solve docker build failure.

**Comment by cybergrind** [comment]
@rhdxmr merged fix for docker, will check PR soon.

**Comment by rhdxmr** [comment]
@cybergrind 
Is there a way to obviate CI build failure by running the build task again?

**Comment by cybergrind** [comment]
@rhdxmr hey, could you please rebase it to pass tests. In general looks fine by me, will release a new version after merge

**Comment by rhdxmr** [comment]
@cybergrind rebased commits are pushed just now.

**Comment by cybergrind** [comment]
@rhdxmr thank you! Released as 0.21.0

**Pull request merged**
